apply plugin: 'com.android.application'

android {
    namespace 'com.benjoo.bsnake'
    compileSdk 33

    defaultConfig {
        applicationId "com.benjoo.bsnake"
        minSdk 16
        targetSdk 33
        versionCode 18
        versionName "1.5.7"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
