apply plugin: 'com.android.application'

android {
    namespace = 'com.benjoo.bsnake'
    compileSdk = 34

    defaultConfig {
        applicationId "com.benjoo.bsnake"
        minSdk = 16
        targetSdk = 34
        versionCode 20
        versionName "1.6.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
